### ISSUE TITLE
android build FAILED on running assembleAndroidTest

### ISSUE THREAD

**Issue by MohamedHamedLab** [getsocial-im/getsocial-react-native-sdk#38]
### Environment
`
   "react-native": "0.66.3",
    "getsocial-react-native-sdk": "^7.9.1",
`
build.gradle

`
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31 
        ndkVersion = "21.4.7075529"
        kotlinVersion = '1.4.21'
     }
 // build version
    dependencies {

        classpath("com.android.tools.build:gradle:7.0.4")
}
`

### Command
`
./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug
`
### Expected Result
Should build correctly 

### Actual Result

`
Task :getsocial-react-native-sdk:processDebugAndroidTestManifest FAILED

/node_modules/getsocial-react-native-sdk/android/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest3321171606387744936.xml Error:
        Attribute data@host at tempFile1ProcessTestManifest3321171606387744936.xml requires a placeholder substitution but no value for <getsocial_hostName_0> is provided.
/node_modules/getsocial-react-native-sdk/android/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest3321171606387744936.xml Error:
        Attribute data@host at tempFile1ProcessTestManifest3321171606387744936.xml requires a placeholder substitution but no value for <getsocial_hostName_1> is provided.
/node_modules/getsocial-react-native-sdk/android/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest3321171606387744936.xml Error:
        Attribute data@host at tempFile1ProcessTestManifest3321171606387744936.xml requires a placeholder substitution but no value for <getsocial_scheme> is provided.
`

**Comment by demiandenker** [comment]
It looks like you have done a manual integration instead of following the steps in our docs to use the GetSocial gradle plugin:
https://docs.getsocial.im/guides/getting-started/react-native/

If that was on purpose then you need to follow the steps for manual integration:
https://docs.getsocial.im/knowledge-base/manual-integration/android/

In particular, the error you mentioned, is caused by not following the steps of manual integration, specially this one to update the manifest manifestPlaceholders:
https://docs.getsocial.im/knowledge-base/manual-integration/android/#configure-manifest

It should end up looking like this if you didn't set up a custom domain

`manifestPlaceholders = [getsocial_scheme:"[app_id]", getsocial_hostName_0:"[your_app_prefix].gsc.im", getsocial_hostName_1:"[your_app_prefix]-gsalt.gsc.im"]`

Or like this when you do have a custom domain for Smart Invites

`manifestPlaceholders = [getsocial_scheme:"[app_id]", getsocial_hostName_0:"[your_app_custom_domain]", getsocial_hostName_1:"[your_app_prefix].gsc.im"]`

Your `appId` and `app prefix` are available inside your GetSocial Dashboard
